name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production
          
      - name: Run tests (if available)
        run: |
          if [ -f "package.json" ] && grep -q '"test"' package.json; then
            pnpm test
          else
            echo "No tests found, skipping..."
          fi
        continue-on-error: true
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: out
          # å¦‚æžœä½¿ç”¨ Next.js static exportï¼Œè¼¸å‡ºç›®éŒ„ç‚º 'out'
          # å¦‚æžœä½¿ç”¨å…¶ä»–æ¡†æž¶ï¼Œè«‹èª¿æ•´ç‚ºå°æ‡‰çš„å»ºç½®è¼¸å‡ºç›®éŒ„
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add deployment comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: deployment } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            if (deployment.length > 0) {
              const deploymentUrl = `https://${context.payload.pull_request.head.sha}.${process.env.CF_PROJECT_NAME}.pages.dev`;
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `ðŸš€ **éƒ¨ç½²é è¦½å·²æº–å‚™å°±ç·’ï¼**
                
é è¦½ç¶²å€ï¼š${deploymentUrl}

æ­¤é è¦½æœƒåœ¨ PR åˆä½µå¾Œè‡ªå‹•ç§»é™¤ã€‚`
              });
            }
        env:
          CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
          
  # å¯é¸ï¼šå®‰å…¨æ€§æŽƒæ
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run security audit
        run: pnpm audit --audit-level moderate
        continue-on-error: true
        
      - name: Check for vulnerabilities
        run: |
          if command -v npm &> /dev/null; then
            npm audit --audit-level high
          fi
        continue-on-error: true

